version: '3'
services:
  master:
    image: mohalahmad/spark:1.1
    networks: 
      - overlay-spark
    environment:
      - masterIP=172.28.5.5
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports: 
      - "4040:4040"
      - "7077:7077"
      - "6066:6066"
      - "8085:8080"
      
  slave:
    image: slavespark:1.0
    depends_on:
      - spark_master
    networks: 
      - overlay-spark
    environment:
      - masterURL=spark://172.28.5.5:7077
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports: 
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
networks:
    overlay-spark:
        external: true
